export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as Testimonials } from './Testimonials'
export { default as Newsletter } from './Newsletter'
export { default as Courses } from './Courses'
export { default as BestChoices } from './BestChoices'
export { default as Events } from './Events'
